projectName: "nldi"
applicationName: "nldi-services"
dockerImageName: "nldi-services"
containerPort: 8080
artifactoryPath: "nldi"
gitlabPath: "wma/docker/nldi"
gitRepoPath: "https://github.com/ACWI-SSWD/nldi-services.git"
gitRepoCredentialsId: "GITHUB_ACCESS_TOKEN"
memory: 768
rulePriority: 10
healthCheck: "/nldi/swagger-ui.html"
contextPath: "/nldi/*"
deployJobName: "NLDI-services-container-deploy"
