spring:
  datasource:
    url: "jdbc:postgresql://${nldiDbHost}:${nldiDbPort}/nldi"
    username: ${nldiDbUsername}
    password: ${nldiDbPassword}
    driver-class-name: org.postgresql.Driver

  profiles:
    active: default,swagger

server:
  port: ${serverPort}
  servlet:
    context-path: ${serverContextPath}

nldi:
  displayProtocol: ${nldiProtocol}
  displayHost: ${nldiHost}
  displayPath: ${nldiPath:}
